apiVersion: v1
kind: Service
metadata:
  name: onlinebookstoreapp-service
spec:
  ports:
  - port: 80
    targetPort: onlinebookstoreapp-port
    protocol: TCP
  selector:
    app: 
  type: LoadBalancer
