apiVersion: v1
kind: Service
metadata:
  name: onlinebookstoredb-service
spec:
  ports:
  - port: 3306
    targetPort: onlinebookstoredb-port
    protocol: TCP
  selector:
    app: onlinebookstoredb
  type: ClusterIP
